server:
  port: 8443

  ssl:
    key-store: classpath:keystore.jks
    key-store-password: tomcat
    key-password: tomcat

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/playground?autoReconnect=true&noDatetimeStringSync=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf8&useUnicode=true&mysqlEncoding=utf8&noAccessToProcedureBodies=true
    username: root
    password: gkslskfk
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1

  data:
    rest:
      base-path: /api

  h2:
    console:
      enabled: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      #ddl-auto: create-drop
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy

security:
  user:
    name: red
    password: red

  oauth2:
    resource:
      filter-order: 3

flyway:
  enabled: true
  check-location: true # 마이그레이션 스크립트 파일이 존재하는지 여부를 확인
  baseline-on-migrate: true
  encoding: UTF-8
  locations: classpath:db/migration # 마이그레이션 스크립트 위치
  sql-migration-prefix: V
  sql-migration-suffix: .sql

info:
  app:
    name: 스프링 부트 샘플
    description: 액추에이터 모듈
    version: 1.0.0

endpoints:
  beans:
    sensitive: false

management:
  context-path: /monitor
